#pragma once
#include "../utils/Error.h"
#define  RRIVATE_MESSAGE (utils::Error::IsChinese() ? std::string("[密聊消息]"):std::string("[Private Message]"))
#define  INSTRUCT_EMOJI_TIP (utils::Error::IsChinese() ? std::string("[指令表情: ") :std::string("[Instruction: "))
#define  SHAKE_TIP			(utils::Error::IsChinese() ? std::string("[抖一抖]"):std::string("Nudge]"))
#define  ERASER_TIP			(utils::Error::IsChinese() ? std::string("[橡皮擦]"):std::string("Eraser]"))
#define IMAGE_MSG_TIP		(utils::Error::IsChinese() ? std::string("[图片]"):std::string("[Images]"))
#define AUDIO_MSG_TIP		(utils::Error::IsChinese() ? std::string("[音频]"):std::string("[Audio]"))
#define CARD_MSG_TIP		(utils::Error::IsChinese() ? std::string("[名片]"):std::string("[Name Card]"))
#define  FILE_MSG_TIP		(utils::Error::IsChinese() ? std::string("[文件]"):std::string("[Files]"))
#define  COMBIN_MSG_TIP		(utils::Error::IsChinese() ? std::string("[消息记录]"):std::string("[Combination Messages]"))
#define  TEMPLATE_MSG_TIP		(utils::Error::IsChinese() ? std::string("[模板消息]"):std::string("[Template Messages]"))
#define  IMAGE_MSG_MICRO_VIDEO	(utils::Error::IsChinese() ? std::string("[微视频]"):std::string("[Mini Video]"))
#define  MSG_VIDEOONLINE_TIP	(utils::Error::IsChinese() ? std::string("[视频消息]"):std::string("[Video Messages]"))
#define  MSG_AUDIOONLINE_TIP	(utils::Error::IsChinese() ? std::string("[音频消息]"):std::string("[Audio Messages]"))
#define  POSITION_MSG_TIP		(utils::Error::IsChinese() ? std::string("[位置]"):std::string("[Location]"))
#define  RECALL_TIP_MSG         (utils::Error::IsChinese() ? std::string("[撤回]"):std::string("[Recall]"))
#define  PROMPT_MSG_TIP			(utils::Error::IsChinese() ? std::string("消息提示"):std::string("[Notice]"))
#define  DYNAMIC_EMOJI_MSG		(utils::Error::IsChinese() ? std::string("[动态表情]"):std::string("[Emotions]"))
#define  IMAGE_TXT_MSG		(utils::Error::IsChinese() ? std::string("[图文消息]"):std::string("[Text Message]"))
#define  WEBLINK_MSG   (utils::Error::IsChinese() ? std::string("[网页链接]"):std::string("[Link]")) 
#define  TASK_MSG   (utils::Error::IsChinese() ? std::string("[任务]"):std::string("[Task]")) 
#define  MSG_AUDIOONLINE_TIP (utils::Error::IsChinese() ? std::string("[音频消息]"):std::string("[Audio Messages]"))
#define  MAC_NOT_MSG_AUDIO_TIP	(utils::Error::IsChinese() ? std::string("暂不支持音频消息，请在windows上查看"):std::string("Do not support audio messages, please check on windows"))
#define  UNDEFINE_MSG_TIP (utils::Error::IsChinese() ? std::string("[不支持的消息，可在手机上查看]"):std::string("[Unsupported type,view in phone]"))
#define  EMOJI_TIP (utils::Error::IsChinese() ? std::string("<表情>") :std::string("<Emotion>"))
#define  BURN_MSG_TIP (utils::Error::IsChinese() ? std::string("[阅后即焚]") :std::string("<Burn Messages>"))
#define  MY_DEVICE  (utils::Error::IsChinese() ? QString::fromLocal8Bit("我的设备") :QString::fromLocal8Bit("My device"))
