const DOOD_EMOJI = [
  { class: ':dood_weixiao:', name: '[微笑]', enname: '[Smile]', code: 'weixiao' },
  { class: ':dood_se:', name: '[色]', enname: '[Drool]', code: 'se' },
  { class: ':dood_deyi:', name: '[得意]', enname: '[Smug]', code: 'deyi' },
  { class: ':dood_liulei:', name: '[流泪]', enname: '[Tears]', code: 'liulei' },
  { class: ':dood_haixiu:', name: '[害羞]', enname: '[Shy]', code: 'haixiu' },
  { class: ':dood_bizui:', name: '[闭嘴]', enname: '[Slience]', code: 'bizui' },
  { class: ':dood_shuijiao:', name: '[睡]', enname: '[Sleep]', code: 'shui' },
  { class: ':dood_ganga:', name: '[尴尬]', enname: '[Awkward]', code: 'ganga' },
  { class: ':dood_fanu:', name: '[发怒]', enname: '[Angry]', code: 'fanu' },
  { class: ':dood_wulian:', name: '[捂脸]', enname: '[Face]', code: 'wulian' },

  { class: ':dood_tiaopi:', name: '[调皮]', enname: '[Naughty]', code: 'tiaopi' },
  { class: ':dood_ciya:', name: '[呲牙]', enname: '[Grin]', code: 'ciya' },
  { class: ':dood_jinya:', name: '[惊讶]', enname: '[Surprise]', code: 'jingya' },
  { class: ':dood_zhuakaung:', name: '[抓狂]', enname: '[Scream]', code: 'zhuakuang' },
  { class: ':dood_touxiao:', name: '[偷笑]', enname: '[Titter]', code: 'touxiao' },
  { class: ':dood_baiyan:', name: '[白眼]', enname: '[Slight]', code: 'baiyan' },
  { class: ':dood_zuohengheng:', name: '[左哼哼]', enname: '[BahLeft]', code: 'zuohengheng' },
  { class: ':dood_liuhan:', name: '[流汗]', enname: '[Speechless]', code: 'liuhan' },
  { class: ':dood_yiwen:', name: '[疑问]', enname: '[Question]', code: 'yiwen' },
  
  { class: ':dood_bugaoxin:', name: '[不高兴]', enname: '[Unhappy]', code: 'bugaoxing' },
  { class: ':dood_yun:', name: '[晕]', enname: '[Dizzy]', code: 'yun' },
  { class: ':dood_fenle:', name: '[疯了]', enname: '[Crazy]', code: 'fengle' },
  { class: ':dood_qiaoda:', name: '[敲打]', enname: '[Hammer]', code: 'qiaoda' },
  { class: ':dood_shuai:', name: '[衰]', enname: '[Unlucky]', code: 'shuai' },
  { class: ':dood_zaijian:', name: '[再见]', enname: '[Bye]', code: 'zaijian' },
  { class: ':dood_koubi:', name: '[抠鼻]', enname: '[NosePick]', code: 'koubi' },
  { class: ':dood_guzhang:', name: '[鼓掌]', enname: '[Applaud]', code: 'guzhang' },
  { class: ':dood_youhengheng:', name: '[右哼哼]', enname: '[BahRight]', code: 'youhengheng' },
  
  { class: ':dood_bishi:', name: '[鄙视]', enname: '[Disdain]', code: 'bishi' },
  { class: ':dood_weiqu:', name: '[委屈]', enname: '[Grievance]', code: 'weiqu' },
  { class: ':dood_yingxian:', name: '[阴险]', enname: '[Sly]', code: 'yinxian' },
  { class: ':dood_qingqing:', name: '[亲亲]', enname: '[Kiss]', code: 'qinqin' },
  { class: ':dood_kelian:', name: '[可怜]', enname: '[Pitiful]', code: 'kelian' },
  { class: ':dood_aida:', name: '[挨打]', enname: '[Beating]', code: 'aida' },
  { class: ':dood_aoman:', name: '[傲慢]', enname: '[Arrogance]', code: 'aoman' },
  { class: ':dood_buxie:', name: '[不屑]', enname: '[Scorn]', code: 'buxie' },
  { class: ':dood_daxiao:', name: '[大笑]', enname: '[Laughter]', code: 'daxiao' },
  
  { class: ':dood_heng:', name: '[哼]', enname: '[Hummed]', code: 'heng' },
  { class: ':dood_huachi:', name: '[花痴]', enname: '[Anthomaniac]', code: 'huachi' },
  { class: ':dood_huaixiao:', name: '[坏笑]', enname: '[BadSmile]', code: 'huaixiao' },
  { class: ':dood_ku:', name: '[哭]', enname: '[Cry]', code: 'ku' },
  { class: ':dood_kun:', name: '[困]', enname: '[Tired]', code: 'kun' },
  { class: ':dood_lenghan:', name: '[冷汗]', enname: '[ColdSweat]', code: 'lenghan' },
  { class: ':dood_nanguo:', name: '[难过]', enname: '[Sad]', code: 'nanguo' },
  { class: ':dood_nu:', name: '[怒]', enname: '[Rage]', code: 'nu' },
  { class: ':dood_qiexiao:', name: '[窃笑]', enname: '[Snickered]', code: 'qiexiao' },

  { class: ':dood_huaxiao:', name: '[吓]', enname: '[Threaten]', code: 'xia' },
  { class: ':dood_xu:', name: '[嘘]', enname: '[Sh]', code: 'xu' },
  { class: ':dood_zhemo:', name: '[折磨]', enname: '[Torment]', code: 'zhemo' }
]
export default DOOD_EMOJI