const DYNAMIC_EMOJI = [
  { name: '到', code: 'Dynamic_Expression_25.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_25.gif') },
  { name: '开会啦', code: 'Dynamic_Expression_23.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_23.gif') },
  { name: '八嘎', code: 'Dynamic_Expression_22.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_22.gif') },
  { name: '加油', code: 'Dynamic_Expression_06.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_06.gif') },
  { name: '鼓掌', code: 'Dynamic_Expression_29.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_29.gif') },
  { name: '嗯嗯', code: 'Dynamic_Expression_18.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_18.gif') },
  { name: '赞', code: 'Dynamic_Expression_28.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_28.gif') },
  { name: '亚历山大', code: 'Dynamic_Expression_27.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_27.gif') },
  { name: '老天保佑', code: 'Dynamic_Expression_24.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_24.gif') },
  { name: '干杯', code: 'Dynamic_Expression_20.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_20.gif') },
  { name: '幸会', code: 'Dynamic_Expression_26.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_26.gif') },
  { name: '无聊', code: 'Dynamic_Expression_12.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_12.gif') },
  { name: '谢谢', code: 'Dynamic_Expression_13.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_13.gif') },
  { name: '回家', code: 'Dynamic_Expression_19.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_19.gif') },
  { name: '数钱', code: 'Dynamic_Expression_10.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_10.gif') },
  { name: '再见', code: 'Dynamic_Expression_14.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_14.gif') },
  { name: '哈哈', code: 'Dynamic_Expression_17.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_17.gif') },
  { name: '大哭', code: 'Dynamic_Expression_04.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_04.gif') },
  { name: '抠鼻', code: 'Dynamic_Expression_07.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_07.gif') },
  { name: '雷劈', code: 'Dynamic_Expression_08.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_08.gif') },
  { name: '抓狂', code: 'Dynamic_Expression_15.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_15.gif') },
  { name: '臭美', code: 'Dynamic_Expression_16.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_16.gif') },
  { name: '挤成狗', code: 'Dynamic_Expression_21.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_21.gif') },
  { name: '哼哼', code: 'Dynamic_Expression_05.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_05.gif') },
  { name: '抱抱', code: 'Dynamic_Expression_01.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_01.gif') },
  { name: '蹭蹭', code: 'Dynamic_Expression_02.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_02.gif') },
  { name: '吃饭', code: 'Dynamic_Expression_03.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_03.gif') },
  { name: '亲亲', code: 'Dynamic_Expression_09.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_09.gif') },
  { name: '睡觉', code: 'Dynamic_Expression_11.gif', img: require('vrv-static/resources/images/emoji/text_emoji/Dynamic_Expression_11.gif') }
]
export default DYNAMIC_EMOJI